// Code generated by "stringer -type=PathType"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParsePathZero-0]
	_ = x[ParsePathLang-1]
	_ = x[ParsePathDomain-2]
	_ = x[ParsePathDomainLang-3]
	_ = x[ParsePathDomainSite-4]
	_ = x[ParsePathDomainSiteLang-5]
	_ = x[ParsePathDomainSiteLangAppName-6]
}

const _PathType_name = "ParsePathZeroParsePathLangParsePathDomainParsePathDomainLangParsePathDomainSiteParsePathDomainSiteLangParsePathDomainSiteLangAppName"

var _PathType_index = [...]uint8{0, 13, 26, 41, 60, 79, 102, 132}

func (i PathType) String() string {
	if i < 0 || i >= PathType(len(_PathType_index)-1) {
		return "PathType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathType_name[_PathType_index[i]:_PathType_index[i+1]]
}
